version: '3'

services: 

  app:
    build: .
    command: yarn dev
    volumes: 
      - .:/usr/app
    ports: 
      - 3000:3000
    environment:
      DB_HOST: postgresdb
      DB_USERNAME: postgres
      DB_PASSWORD: 1234567 
    depends_on: 
      - postgresdb

  postgresdb:
    image: postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234567

volumes:
  postgres: