GET http://localhost:3000/clients

###

POST http://localhost:3000/clients
content-type: application/json

{
    "name": "Miguel Prado"
}

###

GET http://localhost:3000/clients/1

###

GET http://localhost:3000/clients/1/creditcards

###

DELETE http://localhost:3000/clients/3

###

PUT  http://localhost:3000/clients/4
content-type: application/json

{
    "name": "Miguel Prado Teste"
}